services:
  app:
    container_name: load-forecasting-dashboard
    #    image: iccs/load-forecasting-dashboard:0.1
    restart: always
    build:
      context: "./"
    volumes:
      - ./src:/app/src
    ports:
      - '3003:3000'
    stdin_open: true
    networks:
      - keycloak_net
    # environment:
    #   - REACT_APP_AUTH=False
    env_file:
      - ./.env

networks:
 keycloak_net:
   external: true
