app:
  # host: deeptsf.dev.deployai.eu
  service:
    name: deeptsf-dashboard
  image:
    repository: harbor.aiodp.ai/iccs/deeptsf-dashboard
    tag: latest
    # resources:
    #   requests:
    #     memory: "2Gi"
    #     cpu: "1000m"
    #   limits:
    #     memory: "8Gi"
    #     cpu: "3000m"

  envFromSecrets:
    secretName: deeptsf-dashboard-secrets
  env:
    host: ""
    CHOKIDAR_USEPOLLING: "true"
    REACT_APP_NAME: "Load_Forecasting_Dashboard"
    REACT_APP_AUTH: "True"  # Set to "True" to enable Keycloak authentication
    REACT_APP_BACKEND_BASE_URL: ""
    REACT_APP_MLFLOW: ""
    REACT_APP_KEYCLOAK_REALM: "master"
    REACT_APP_KEYCLOAK_URL: "https://keycloak.toolbox.epu.ntua.gr/"
    REACT_APP_KEYCLOAK_CLIENT_ID: ""
    REACT_APP_DAGSTER_ENDPOINT_URL: ""
    REACT_APP_BACKEND_WS_URL: ""
  replicas: 1
  memory_limit: 4Gi
  commitHash: ""

ingress:
  enabled: true
  tlsSecretName: deeptsf-dashboard-tls
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
