kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.service.name }}-cm
data:
  CHOKIDAR_USEPOLLING: "{{ .Values.app.env.CHOKIDAR_USEPOLLING }}"
  REACT_APP_NAME: "{{ .Values.app.env.REACT_APP_NAME }}"
  REACT_APP_AUTH: "{{ .Values.app.env.REACT_APP_AUTH }}"
  REACT_APP_MLFLOW: "{{ .Values.app.env.REACT_APP_MLFLOW }}"
  REACT_APP_KEYCLOAK_REALM: "{{ .Values.app.env.REACT_APP_KEYCLOAK_REALM }}"
  REACT_APP_KEYCLOAK_URL: "{{ .Values.app.env.REACT_APP_KEYCLOAK_URL }}"
  REACT_APP_KEYCLOAK_CLIENT_ID: "{{ .Values.app.env.REACT_APP_KEYCLOAK_CLIENT_ID }}"
  REACT_APP_DAGSTER_ENDPOINT_URL: "{{ .Values.app.env.REACT_APP_DAGSTER_ENDPOINT_URL }}"
  REACT_APP_BACKEND_BASE_URL: "{{ .Values.app.env.REACT_APP_BACKEND_BASE_URL }}"
  REACT_APP_BACKEND_WS_URL: "{{ .Values.app.env.REACT_APP_BACKEND_WS_URL }}"
