apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.service.name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, x-requested-with"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"  # Use "HTTPS" if TLS is terminated at service
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"  # Increase to allow larger uploads
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "75"
    nginx.ingress.kubernetes.io/proxy-read-timeout:  "7200"
    nginx.ingress.kubernetes.io/proxy-send-timeout:  "7200"
  labels:
    release: {{ .Release.Name }}

spec:
  tls:
    - hosts:
        - {{ .Values.app.env.host }}
      secretName: "{{ .Release.Name }}-tls"
  rules:
    - host: {{ .Values.app.env.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-{{ .Values.app.service.name }}"
                port:
                  number: 80
